version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/home/node/app
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: codingducks-backend
    expose:
      - "3333"
    ports:
      - "3333:3333"
    command: yarn dev
