version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: codingducks-backend
    volumes:
      - ./:/app
      - ./nodemon.json:/app/nodemon.json
    deploy:
      resources:
        limits:
          memory: 800M

    expose:
      - "3333"
      - "3334"
    ports:
      - "3333:3333"
      - "3334:3334"
    command: yarn dev
