version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    container_name: codingducks-backend
    volumes:
      - ./:/app
      - ./nodemon.json:/app/nodemon.json
      - /app/node_modules
    restart: always
    deploy:
      resources:
        limits:
          memory: 2.5g

    expose:
      - "3333"
      - "3334"
    ports:
      - "3333:3333"
      - "3334:3334"
    command: yarn dev
