version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/app
      - ./nodemon.json:/app/nodemon.json
    container_name: codingducks-backend
    expose:
      - "3333"
      - "3334"
    ports:
      - "3333:3333"
      - "3334:3334"
    command: yarn start
